// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8lzpCo27FXgFkN0aKow_pvIMrnTpwbs',
    appId: '1:332684033159:android:dafee62ae03fecd8c18c22',
    messagingSenderId: '332684033159',
    projectId: 'new-humph',
    storageBucket: 'new-humph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2gensagF9d_E4dXTxD3qI7FhdvLq8_0',
    appId: '1:332684033159:ios:7b717d27193e75b4c18c22',
    messagingSenderId: '332684033159',
    projectId: 'new-humph',
    storageBucket: 'new-humph.firebasestorage.app',
    iosBundleId: 'com.example.humphreys',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtLcCpTEYUTDoFb5dw_jacvy-2Thl0sQ',
    appId: '1:332684033159:web:75fd1d0835e5ec86c18c22',
    messagingSenderId: '332684033159',
    projectId: 'new-humph',
    authDomain: 'new-humph.firebaseapp.com',
    storageBucket: 'new-humph.firebasestorage.app',
    measurementId: 'G-GHTMZR1RBB',
  );

}