// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxZYVAm6oQSyEwNQNg172-bWMZFUxdcc',
    appId: '1:245291959182:web:4f98274d797cadb7d21adf',
    messagingSenderId: '245291959182',
    projectId: 'humphreys-firebase',
    authDomain: 'humphreys-firebase.firebaseapp.com',
    storageBucket: 'humphreys-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCeGR94z5Rt6yTVHCHLefVRi5R7CDc38',
    appId: '1:245291959182:android:fd45fe66f4a841b9d21adf',
    messagingSenderId: '245291959182',
    projectId: 'humphreys-firebase',
    storageBucket: 'humphreys-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgWtlUHZs7FxDcyTfdcPpSe1PQChaFnI',
    appId: '1:245291959182:ios:395753697fc8a9f9d21adf',
    messagingSenderId: '245291959182',
    projectId: 'humphreys-firebase',
    storageBucket: 'humphreys-firebase.appspot.com',
    iosClientId: '245291959182-ujg4s9deeh9d8fr732e9v3bbpu6ns2sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.humphreys',
  );
}
